repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.3
    hooks:
    -   id: python-bandit-vulnerability-check
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: requirements-txt-fixer
# -   repo: git://github.com/FalconSocial/pre-commit-python-sorter
#     rev: 1.0.4
#     hooks:
#     -   id: python-import-sorter
#         args: ['--silent-overwrite']
# -   repo: https://github.com/jorisroovers/gitlint
#     rev: v0.10.0
#     hooks:
#     -   id: gitlint
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: fix-encoding-pragma
# -   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#     rev: v1.1.0
#     hooks:
#     -   id: python-safety-dependencies-check
