language: python
python:
  - "3.6"

before_install:
  # - sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  # - sudo tar -xvzf geckodriver*
  # - sudo chmod +x geckodriver
  # - export PATH=$PATH:.
  - sudo add-apt-repository ppa:fkrull/deadsnakes -y
  - sudo apt-get update
  - sudo apt-get install python3.6
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - python manage.py test lists
after_success:
  - codecov
